import { Nata_Sans, Raleway } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";


const nataSans = Nata_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable:"--font-nata-sans",
  display: "swap",
});

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable:"--font-raleway",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nataSans.variable} ${raleway.variable}`}>
        {/* header will go here */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}
